#!/bin/sh

CURRENT_BRANCH=`git rev-parse --abbrev-ref HEAD`

npm run bundle:test
git add browser-test-bundle.js

if [ $CURRENT_BRANCH == "wip-solution" ] || [ $CURRENT_BRANCH == "solution" ]
then
    npm test
fi
